### ISSUE TITLE
CoMotion: 2nd joystick doesn't work in 2P mode

### ISSUE THREAD

**Issue by KremlingKuthroat19** [MiSTer-devel/Arcade-Blockade_MiSTer#9]
When prompted to enter $0.25 for a 2P game or $0.50 for a 4P game, and you choose the former, the second joystick is non-functional. When choosing 4P mode, all four joysticks work properly though. TLDR; player 2 doesn't work in 2P mode :)

**Comment by JimmyStones** [comment]
In 4P mode, can you tell me which joystick controls which player?  e.g. 1 is Top, 2 is Bottom etc.  I don't have enough input devices to do a proper test!

I reckon by the sounds of it maybe the inputs for 2 and 3 are the wrong way round.

**Comment by KremlingKuthroat19** [comment]
After some testing P3 works as the second controller in 2P mode. 1P is the top, 3P is the bottom. I guess 3P and 2P should swap places and it'd fix this issue

**Comment by JimmyStones** [comment]
@KremlingKuthroat19 this should now be fixed by latest release, do let me know if not though...  cheers for the report :)

**Comment by KremlingKuthroat19** [comment]
@JimmyStones Just tested all four games to make sure they work with no regressions. Every game works as intended now. CoMotion works in 2P mode with controller 2 and in 4P mode. Core is perfect now. Thanks!
